{{- if and .Values.ingress.enabled (eq .Values.ingress.className "nginx") }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "apigateway.fullname" . }}
  annotations:
    #kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: {{ .Values.ingress.className | default "alb" | quote }}
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ .host }}
      http:
        paths:
        {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "apigateway.fullname" $ }}
                port:
                  number: {{ $.Values.service.port }}
        {{- end }}
  {{- end }}
{{- end }}