helm:
  parameters:
  - name: image.repository
    value: 085980781371.dkr.ecr.ap-east-2.amazonaws.com/apigateway
    forcestring: true
  - name: image.tag
    value: sha-249bece1324f02db60af25cbc59e52c744e3bc84
    forcestring: true
