nameOverride: ""
fullnameOverride: ""

image:
  repository: 085980781371.dkr.ecr.ap-east-2.amazonaws.com/apigateway
  tag: "latest"               # managed by Image Updater (semver)
  pullPolicy: IfNotPresent

replicaCount: 2

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

# HTTP probes for REST endpoint
probes:
  path: /healthz
  port: 8080

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

env: [
  [ 
    { name: ConnectionStrings__DefaultConnection, 
      value: Host=postgres-postgresql.db.svc.cluster.local;Port=5432;Database=MicroService;Username=gino;Password=@a123456 }, { name: GrpcService__0__Name, value: "User" }
    ,
    { name: GrpcService__0__Url, 
      value: "http://userapi.apps.svc.cluster.local:8080" } ] # e.g. [{ name: ASPNETCORE_ENVIRONMENT, value: Production }]
]  # e.g. [{ name: ASPNETCORE_ENVIRONMENT, value: Production }]

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
  # targetMemoryUtilizationPercentage: 80

ingress:
  enabled: true
  className: alb    # set to "alb" for AWS LB Controller, or "nginx" for NGINX
  hosts:
    - host: ""
      paths:
        - path: /
          pathType: Prefix
  tls: []
  alb:
    scheme: internet-facing           # or "internet-facing"
    listenPorts: '[{"HTTP":80}]'  # example; use HTTPS with certs in production
    targetType: ip
    healthcheckPath: /healthz