image:
  repository: 123456789012.dkr.ecr.ap-east-2.amazonaws.com/userapi
  tag: "1.0.0"                # managed by Image Updater (semver)
  pullPolicy: IfNotPresent

replicaCount: 2

service:
  type: ClusterIP
  port: 50051
  targetPort: 50051
  name: grpc     # important for some ingress controllers

# gRPC health probes (K8s >= 1.24)
probes:
  grpc:
    port: 50051
    service: ""       # optional, defaults to container port

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

env: [
        { name: ConnectionStrings__DefaultConnection,
          value: "Host=postgres-postgresql.db.svc.cluster.local;Port=5432;Database=MicroService;Username=gino;Password=@a123456"
        },
        {
          name: GrpcService__0__Name,
          value: "User"
        },
        {
          name: GrpcService__0__Url,
          value: "http://userapi.apps.svc.cluster.local:8080"
        }
      ]  

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70

ingress:
  enabled: true
  className: alb    # or "nginx"
  hosts:
    - host: userapi.internal.example.com
      paths:
        - path: /
          pathType: Prefix
  tls: []
  alb:
    scheme: internal
    listenPorts: '[{"HTTP":80}]'
    targetType: ip
    backendProtocolVersion: HTTP2  # enable gRPC through ALB