apiVersion: v1
kind: Secret
metadata:
  name: github-creds
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/Gino1024/microServiceDemo-infra.git
  username: Gino1024
  #password: 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
  password: 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