apiVersion: v1
kind: Secret
metadata:
  name: github-creds
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/Gino1024/microServiceDemo-infra.git
  username: Gino1024
  password: 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
  name: github-infra-repo   # ✅ 建議補這個，方便辨識（可隨便取）
  type: git                 # ✅ 建議補這個，明確指定 git