apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apigateway
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Gino1024/microServiceDemo-infra.git
    targetRevision: main
    path: Charts/WebApp/apigateway
    helm:
      releaseName: apigateway
      values: |
        # override namespace-specific env if needed
  destination:
    server: https://kubernetes.default.svc
    namespace: webapp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      